services:
    Gamboa\AdminBundle\EventListener\ViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view }
    Gamboa\AdminBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Gamboa\AdminBundle\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }