services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    gadmin.auth_service:
        class: Gamboa\AdminBundle\Service\AuthService

    Gamboa\AdminBundle\Service\AuthService: '@gadmin.auth_service'

    Gamboa\AdminBundle\EventListener\ViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view }
    Gamboa\AdminBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Gamboa\AdminBundle\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Gamboa\AdminBundle\Controller\:
        resource: '../Controller'
        tags: ['controller.service_arguments']