services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gamboa\AdminBundle\Service\UserService: ~
    Gamboa\AdminBundle\Service\SessionService: ~
    Gamboa\AdminBundle\Service\AuthService: ~

    Gamboa\AdminBundle\EventListener\ViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view }
    Gamboa\AdminBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Gamboa\AdminBundle\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Gamboa\AdminBundle\Command\CrearUsuarioCommand:
        tags: ['console.command', 'controller.service_arguments']

    Gamboa\AdminBundle\Controller\:
        resource: '../Controller'
        tags: ['controller.service_arguments']